---
- hosts: all
  vars:
    a: [1,2,3,4,5]
    b: [2,3]
  tasks:
    - debug: msg="A includes B"
      when: a|issuperset(b)

    - debug: msg="B is included in A"
      when: b|issubset(a)